### ISSUE TITLE
Set color settings only for one display?

### ISSUE THREAD

**Issue by h200101** [9072997/ColorEffectCmd#1]
Hi!
I love this little program. It is exactly what I need, and it works, but the problem is I just need to invert colours only on one display. Can that be done?

**Comment by 9072997** [comment]
see version 2.1 and the new `/w` flag

If you maximize the window it will go full-screen on only one display. Note that there is likely a performance penalty for the way this is implemented (explicitly drawing a window vs. just asking the kernel to color shift everything).

**Comment by h200101** [comment]
Hi!
@9072997 Really nice, the colours are reversed with the /w flag (except the Start menu, but that is totaly fine), but it only draws half of the second monitor...
![slika](https://github.com/9072997/ColorEffectCmd/assets/130376430/40fc93a4-46b6-4aed-ac84-b74d478bf1ab)

My second screen is on the right of the primary monitor. And if I move the second screen to the left, then I have like this:
![slika](https://github.com/9072997/ColorEffectCmd/assets/130376430/2c63877f-3655-4504-979a-03922a979a2c)

The same behaviour is when I put the second monitor up and down. 

But If I change what is the primary display, then it works.
![slika](https://github.com/9072997/ColorEffectCmd/assets/130376430/b37f4fd7-affe-4169-bad8-a938e094bea2)

Thank you :D
